# Generated by Django 5.1.2 on 2024-10-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0003_transaction_is_imported'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordProxy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('booking_date',)},
        ),
        migrations.AddField(
            model_name='transaction',
            name='records',
            field=models.ManyToManyField(to='bank_account.recordproxy'),
        ),
    ]
