# Generated by Django 5.1.2 on 2024-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0006_remove_transaction_is_imported'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordproxy',
            options={'ordering': ('date', 'subject')},
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
