# Generated by Django 5.1.2 on 2024-10-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0007_alter_recordproxy_options_transaction_is_marked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_marked',
            new_name='is_highlighted',
        ),
    ]
