# Generated by Django 5.1.2 on 2024-11-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0010_remove_transaction_is_ready_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordproxy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='records',
            field=models.ManyToManyField(related_name='transactions', to='bank_account.recordproxy'),
        ),
    ]
