# Generated by Django 5.1.2 on 2025-01-02 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0013_alter_account_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
